import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-pallet-pooling-reusable-packaging-recovery",
  "engine": "recovery",
  "title": "Pallet Pooling & Reusable Packaging Recovery",
  "shortTitle": "Pallet Pooling and Reusable Packaging Recovery",
  "tagline": "Quantify, recover, and prevent financial leakage through pallet pooling & reusable packaging recovery",
  "industry": "Reusable Asset Financial Operations",
  "uiPort": 4608,
  "apiPort": 5608,
  "accent": "#4338ca",
  "currency": "USD",
  "primaryOutcome": "Pallet Pooling & Reusable Packaging Recovery converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect pooling agreements, asset types, serialized assets, shipments, transfers, partner balances, hire days, damage, depot receipts, invoices, credits, and recoveries in one accountable recovery workflow.",
  "calculation": {
    "actualKey": "chargedAmount",
    "expectedKey": "supportedAmount",
    "actualLabel": "Pooling Charges",
    "expectedLabel": "Supported Hire and Loss Cost",
    "varianceLabel": "Potential recovery or avoided cost",
    "direction": "actual-minus-expected",
    "finding": "Pallet Pooling & Reusable Packaging Recovery evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective governing agreement and applicable rules",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare and submit the recovery or correction package",
      "Track counterparty response and reconcile realized outcome"
    ]
  }
},[
feature("asset-rate-library","PPR01","Asset rate library","Execute asset rate library using pooling agreements, asset types, serialized assets, shipments, transfers, partner balances, hire days, damage, depot receipts, invoices, credits, and recoveries.","Produce a governed asset rate library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Pool Provider / Asset Population","text","Pool Provider / Asset Population · Standard Case"],["caseReference","Asset rate library Reference","text","PPR01-2026-001"],["chargedAmount","Pooling Charges","currency",734500],["supportedAmount","Supported Hire and Loss Cost","currency",631670],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"chargedAmount",subjects:["Asset rate library case","Serialized pooled registry case","Shipment transfer ingestion case","Trading partner balances case","Daily hire calculation case"]}),
feature("serialized-pooled-registry","PPR02","Serialized pooled registry","Execute serialized pooled registry using pooling agreements, asset types, serialized assets, shipments, transfers, partner balances, hire days, damage, depot receipts, invoices, credits, and recoveries.","Produce a governed serialized pooled registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Pool Provider / Asset Population","text","Pool Provider / Asset Population · Standard Case"],["caseReference","Serialized pooled registry Reference","text","PPR02-2026-001"],["chargedAmount","Pooling Charges","currency",734500],["supportedAmount","Supported Hire and Loss Cost","currency",631670],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"chargedAmount",subjects:["Asset rate library case","Serialized pooled registry case","Shipment transfer ingestion case","Trading partner balances case","Daily hire calculation case"]}),
feature("shipment-transfer-ingestion","PPR03","Shipment transfer ingestion","Execute shipment transfer ingestion using pooling agreements, asset types, serialized assets, shipments, transfers, partner balances, hire days, damage, depot receipts, invoices, credits, and recoveries.","Produce a governed shipment transfer ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Pool Provider / Asset Population","text","Pool Provider / Asset Population · Standard Case"],["caseReference","Shipment transfer ingestion Reference","text","PPR03-2026-001"],["chargedAmount","Pooling Charges","currency",734500],["supportedAmount","Supported Hire and Loss Cost","currency",631670],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"chargedAmount",subjects:["Asset rate library case","Serialized pooled registry case","Shipment transfer ingestion case","Trading partner balances case","Daily hire calculation case"]}),
feature("trading-partner-balances","PPR04","Trading partner balances","Execute trading partner balances using pooling agreements, asset types, serialized assets, shipments, transfers, partner balances, hire days, damage, depot receipts, invoices, credits, and recoveries.","Produce a governed trading partner balances decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Pool Provider / Asset Population","text","Pool Provider / Asset Population · Standard Case"],["caseReference","Trading partner balances Reference","text","PPR04-2026-001"],["chargedAmount","Pooling Charges","currency",734500],["supportedAmount","Supported Hire and Loss Cost","currency",631670],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"chargedAmount",subjects:["Asset rate library case","Serialized pooled registry case","Shipment transfer ingestion case","Trading partner balances case","Daily hire calculation case"]}),
feature("daily-hire-calculation","PPR05","Daily hire calculation","Execute daily hire calculation using pooling agreements, asset types, serialized assets, shipments, transfers, partner balances, hire days, damage, depot receipts, invoices, credits, and recoveries.","Produce a governed daily hire calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Pool Provider / Asset Population","text","Pool Provider / Asset Population · Standard Case"],["caseReference","Daily hire calculation Reference","text","PPR05-2026-001"],["chargedAmount","Pooling Charges","currency",734500],["supportedAmount","Supported Hire and Loss Cost","currency",631670],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"chargedAmount",subjects:["Asset rate library case","Serialized pooled registry case","Shipment transfer ingestion case","Trading partner balances case","Daily hire calculation case"]}),
feature("lost-asset-validation","PPR06","Lost asset validation","Execute lost asset validation using pooling agreements, asset types, serialized assets, shipments, transfers, partner balances, hire days, damage, depot receipts, invoices, credits, and recoveries.","Produce a governed lost asset validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Pool Provider / Asset Population","text","Pool Provider / Asset Population · Standard Case"],["caseReference","Lost asset validation Reference","text","PPR06-2026-001"],["chargedAmount","Pooling Charges","currency",734500],["supportedAmount","Supported Hire and Loss Cost","currency",631670],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"chargedAmount",subjects:["Asset rate library case","Serialized pooled registry case","Shipment transfer ingestion case","Trading partner balances case","Daily hire calculation case"]}),
feature("repair-damage-fee-audit","PPR07","Repair damage fee audit","Execute repair damage fee audit using pooling agreements, asset types, serialized assets, shipments, transfers, partner balances, hire days, damage, depot receipts, invoices, credits, and recoveries.","Produce a governed repair damage fee audit decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Pool Provider / Asset Population","text","Pool Provider / Asset Population · Standard Case"],["caseReference","Repair damage fee audit Reference","text","PPR07-2026-001"],["chargedAmount","Pooling Charges","currency",734500],["supportedAmount","Supported Hire and Loss Cost","currency",631670],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"chargedAmount",subjects:["Asset rate library case","Serialized pooled registry case","Shipment transfer ingestion case","Trading partner balances case","Daily hire calculation case"]}),
feature("transfer-rejection-workflow","PPR08","Transfer rejection workflow","Execute transfer rejection workflow using pooling agreements, asset types, serialized assets, shipments, transfers, partner balances, hire days, damage, depot receipts, invoices, credits, and recoveries.","Produce a governed transfer rejection workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Pool Provider / Asset Population","text","Pool Provider / Asset Population · Standard Case"],["caseReference","Transfer rejection workflow Reference","text","PPR08-2026-001"],["chargedAmount","Pooling Charges","currency",734500],["supportedAmount","Supported Hire and Loss Cost","currency",631670],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"chargedAmount",subjects:["Asset rate library case","Serialized pooled registry case","Shipment transfer ingestion case","Trading partner balances case","Daily hire calculation case"]}),
feature("depot-receipt-reconciliation","PPR09","Depot receipt reconciliation","Execute depot receipt reconciliation using pooling agreements, asset types, serialized assets, shipments, transfers, partner balances, hire days, damage, depot receipts, invoices, credits, and recoveries.","Produce a governed depot receipt reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Pool Provider / Asset Population","text","Pool Provider / Asset Population · Standard Case"],["caseReference","Depot receipt reconciliation Reference","text","PPR09-2026-001"],["chargedAmount","Pooling Charges","currency",734500],["supportedAmount","Supported Hire and Loss Cost","currency",631670],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"chargedAmount",subjects:["Asset rate library case","Serialized pooled registry case","Shipment transfer ingestion case","Trading partner balances case","Daily hire calculation case"]}),
feature("unreturned-asset-alerts","PPR10","Unreturned asset alerts","Execute unreturned asset alerts using pooling agreements, asset types, serialized assets, shipments, transfers, partner balances, hire days, damage, depot receipts, invoices, credits, and recoveries.","Produce a governed unreturned asset alerts decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Pool Provider / Asset Population","text","Pool Provider / Asset Population · Standard Case"],["caseReference","Unreturned asset alerts Reference","text","PPR10-2026-001"],["chargedAmount","Pooling Charges","currency",734500],["supportedAmount","Supported Hire and Loss Cost","currency",631670],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"chargedAmount",subjects:["Asset rate library case","Serialized pooled registry case","Shipment transfer ingestion case","Trading partner balances case","Daily hire calculation case"]}),
feature("invoice-recalculation","PPR11","Invoice recalculation","Execute invoice recalculation using pooling agreements, asset types, serialized assets, shipments, transfers, partner balances, hire days, damage, depot receipts, invoices, credits, and recoveries.","Produce a governed invoice recalculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Pool Provider / Asset Population","text","Pool Provider / Asset Population · Standard Case"],["caseReference","Invoice recalculation Reference","text","PPR11-2026-001"],["chargedAmount","Pooling Charges","currency",734500],["supportedAmount","Supported Hire and Loss Cost","currency",631670],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"chargedAmount",subjects:["Asset rate library case","Serialized pooled registry case","Shipment transfer ingestion case","Trading partner balances case","Daily hire calculation case"]}),
feature("customer-recovery-billing","PPR12","Customer recovery billing","Execute customer recovery billing using pooling agreements, asset types, serialized assets, shipments, transfers, partner balances, hire days, damage, depot receipts, invoices, credits, and recoveries.","Produce a governed customer recovery billing decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Pool Provider / Asset Population","text","Pool Provider / Asset Population · Standard Case"],["caseReference","Customer recovery billing Reference","text","PPR12-2026-001"],["chargedAmount","Pooling Charges","currency",734500],["supportedAmount","Supported Hire and Loss Cost","currency",631670],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"chargedAmount",subjects:["Asset rate library case","Serialized pooled registry case","Shipment transfer ingestion case","Trading partner balances case","Daily hire calculation case"]}),
feature("provider-dispute-workflow","PPR13","Provider dispute workflow","Execute provider dispute workflow using pooling agreements, asset types, serialized assets, shipments, transfers, partner balances, hire days, damage, depot receipts, invoices, credits, and recoveries.","Produce a governed provider dispute workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Pool Provider / Asset Population","text","Pool Provider / Asset Population · Standard Case"],["caseReference","Provider dispute workflow Reference","text","PPR13-2026-001"],["chargedAmount","Pooling Charges","currency",734500],["supportedAmount","Supported Hire and Loss Cost","currency",631670],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"chargedAmount",subjects:["Asset rate library case","Serialized pooled registry case","Shipment transfer ingestion case","Trading partner balances case","Daily hire calculation case"]}),
feature("asset-recovery-ledger","PPR14","Asset recovery ledger","Execute asset recovery ledger using pooling agreements, asset types, serialized assets, shipments, transfers, partner balances, hire days, damage, depot receipts, invoices, credits, and recoveries.","Produce a governed asset recovery ledger decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Pool Provider / Asset Population","text","Pool Provider / Asset Population · Standard Case"],["caseReference","Asset recovery ledger Reference","text","PPR14-2026-001"],["chargedAmount","Pooling Charges","currency",734500],["supportedAmount","Supported Hire and Loss Cost","currency",631670],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"chargedAmount",subjects:["Asset rate library case","Serialized pooled registry case","Shipment transfer ingestion case","Trading partner balances case","Daily hire calculation case"]}),
feature("network-cycle-analytics","PPR15","Network cycle analytics","Execute network cycle analytics using pooling agreements, asset types, serialized assets, shipments, transfers, partner balances, hire days, damage, depot receipts, invoices, credits, and recoveries.","Produce a governed network cycle analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Pool Provider / Asset Population","text","Pool Provider / Asset Population · Standard Case"],["caseReference","Network cycle analytics Reference","text","PPR15-2026-001"],["chargedAmount","Pooling Charges","currency",734500],["supportedAmount","Supported Hire and Loss Cost","currency",631670],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"chargedAmount",subjects:["Asset rate library case","Serialized pooled registry case","Shipment transfer ingestion case","Trading partner balances case","Daily hire calculation case"]})
]);
